# Site settings
author: Kachel Wittig
title: Kachel's Coding Blurg
header-img: img/home-bg.png
email: kjwittig@gmail.com
copyright_name: Kachel Wittig
description: > # this means to ignore newlines until "baseurl:"
  Code code code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: scrptktty
github_username:  scrptktty

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
